# properties 면 더 귀찮게 적음
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: jieun0502@gmail.com
    password: ungjwkbotqivwmkv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    check-template-location: true
    prefix: classpath:templates/
    #    resources
    suffix: .html
    mode: HTML
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3308/facebook
    username: root
    password: koreait
    driver-class-name: org.mariadb.jdbc.Driver
#    url를 보고 설정해주기 때문에 안줘도 상관은 없을것이다 랬는데 안된다
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB
      location: D:/springImg
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1086573330439-0sferfnja6dtif0erpgp70500hkqhclt.apps.googleusercontent.com
            client-secret: or_LukuvkdIedTF-kADAirA-
            scope:
              - profile
              - email
          facebook:
            client-id: 1103202866872648
            client-secret: dfea92377ffb88c38a4e63c1ed769cc4
            scope:
              - email
              - public_profile
          kakao:
            authorization-grant-type: authorization_code
            client-id: a5005c539a9b1af9ec6008864c27d699
            client-secret: sLROXOAbUJew483tE9X0uzrhpKUaUXff
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}" #{registrationId}:kakao
            scope:
              - profile_nickname
              - profile_image
            client-authentication-method: POST
            client-name: Kakao
          naver:
            authorization-grant-type: authorization_code
            client-id: ar0BAcBw_4RWL8x2QFOb
            client-secret: IueW2Uf6wM
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}" #{registrationId}:naver
            scope: name,profile_image
            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: properties
            # JSON 형태에서 "properties"라는 key값에 해당하는 value에 회원 정보가 담겨져있다.
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            # JSON 형태에서 "response"라는 key값에 해당하는 value에 회원 정보가 담겨져있다.
mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  type-aliases-package: com.koreait.facebook
  # 덕분에 편하게적는다 mapper에?

# 톰켓 포트 변경
server:
  port: 8090
#  기본적으로 80으로 날아감